-- Superseded by the existing dev-diet rental schema.
-- The previous version recreated `goods` and `rental` with non-existent
-- group_name/time_confirm/approver_id columns. Existing databases already
-- contain these tables, so this migration intentionally performs no DDL.
